print("whelcome to el chatbot")
print("what can i do for you")
question = input("what can i do for you")
print(f"oh i cant help you with {question} try again")
bob = input("how are you feeling")
print(f"im not a therapist bro im a chatbot")
pizza = input("ask me about how to make pizza")
print ("you put the pizza in an oven doofus")
print("you have run out of questions buy premium for more questions")   
buuy = input("would you like to buy more questions")
print (f"yes {buuy} is a great answer")
print ("please input credit card number [not actually]")
ccn = input("enter card number")
print (f"just to confirm the number is {ccn} correct?")
input("yes or no")
print("congradulations on buying pro")
q1 = input("what would you like to ask")
print(f"{q1} is a very interesting topic i have not learned about")
print("shutting down for maintenence")